# Generated by Django 4.1.5 on 2023-02-08 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0005_fotografia_usuario_alter_fotografia_categoria_and_more'),
        ('galeria', '0006_fotografia_usuario'),
    ]

    operations = [
    ]
